enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
arch = "both"
build-mode = "module"
included-patches = "'Hide Create button' 'Custom theme' 'Unlock Premium' 'Sanitize sharing links' 'Fix third party launchers widgets'"
exclusive-patches = true

[Spotify-Amoled]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
arch = "both"
build-mode = "module"
included-patches = "'Hide Create button' 'Custom theme' 'Unlock Premium' 'Sanitize sharing links' 'Fix third party launchers widgets'"
exclusive-patches = true

[Spotify-Monet]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
arch = "both"
build-mode = "module"
included-patches = "'Hide Create button' 'Custom theme' 'Unlock Premium' 'Sanitize sharing links' 'Fix third party launchers widgets'"
exclusive-patches = true
patcher-args = "-e 'Custom theme' -ObackgroundColor=@android:color/system_neutral1_900 -OoverridePlayerGradientColor=true -ObackgroundColorSecondary=@android:color/system_neutral2_900 -OaccentColor=@android:color/system_accent1_200 -OaccentColorPressed=@android:color/system_accent1_300"
